### ISSUE TITLE
Text with offset

### ISSUE THREAD

**Issue by steff517** [bash0/cewe2pdf#58] opened 2020-12-16 13:25 UTC
In some circumstances the text is not always in the correct position or size.  It affects ~20% of the texts in my book.
Note that I added the black boxes later after taking a screenshot. 

**Original**
![image](https://user-images.githubusercontent.com/1554347/102352630-49ca9180-3fa8-11eb-93cb-97749b0e9ab5.png)

**Converted**
![image](https://user-images.githubusercontent.com/1554347/102354150-74b5e500-3faa-11eb-8fe7-1c5c451c199b.png)

**Source**
https://pastebin.com/XEM0Qqqi

**Conversion log**
https://pastebin.com/fHDtG6mz
The screenshot above is page 10.

**Comment by steff517** [comment] 2020-12-16 13:26
I just noticed that the background seems to be differently scaled or aligned, too.

**Comment by AnEnglishmanInNorway** [comment] 2020-12-16 17:11
My compliments on a nice set of test evidence!
What we are really seeing here is the difference between a commercial project and a casually developed program;-) No spec, no formal requirements or tests, each new user functions as a tester, using whatever features he is used to, and when the user is happy then we're done! 
My first question was whether the "Function" font which I see in the page source is correctly set up. It seems to me that the look of the font in the pdf is very slightly different to the original. But perhaps that's an illusion caused by the different sizes of the pictures; I see you must have added Function to additionalfonts.txt, because it has been registered ok in the log.
One thing I'm very curious about in your HTML are the margin values for the table tag, namely 
`margin-top:44px; margin-bottom:30px; margin-left:30px; margin-right:30px; `
When I put in a text box with the album editor here, I get 5 px margins
`margin-top:5px; margin-bottom:5px; margin-left:5px; margin-right:5px;`
I think this might be the problem area, because I'm fairly sure that the cewe2pdf code does not look at those. Do you have any idea which setting in the editor causes these to change? On my test I had no decoration (eg edge, shadow) on the text box, and I can't see any in your pictures either.

**Comment by steff517** [comment] 2020-12-16 20:34
After more research I found out the following:
The relevant setting for the issue is the margin setting right here:
![image](https://user-images.githubusercontent.com/1554347/102402657-6933df80-3fe5-11eb-8944-fc479c265a79.png)
In this example, by setting it to 25mm, Cewe automatically inflates the textbox.

IN the source, this has the following effect on IndentMargin and VertialIndentMargin
![image](https://user-images.githubusercontent.com/1554347/102403080-0858d700-3fe6-11eb-8182-e4d553ceab76.png)
I'm not really sure why those values are different, since I set only one value in Cewe. 

THe output looks like this
![image](https://user-images.githubusercontent.com/1554347/102402881-b912a680-3fe5-11eb-9bb5-013adebc3c07.png)

This reveals two things:

- Cewe2Pdf doesn't corretly process the IndentMargin and VertialIndentMargin because the text still has no margin left and right. 
- There is an issue with text box alignment which offsets the text in this case

Here is my stripped-down book attached for testing.
[Testbuch.zip](https://github.com/bash0/cewe2pdf/files/5705383/Testbuch.zip)

**Comment by AnEnglishmanInNorway** [comment] 2020-12-17 10:10
I've spent a few hours looking at this, and have introduced handling of the margins (padding) defined for the inside of a text box, in pull request https://github.com/bash0/cewe2pdf/pull/57. 
The original code had what can only be described as a frustrated hack to increase the height of a text box (frame) when the text did not fit vertically in the frame. That hack remains in place, I am just as frustrated about why it is necessary. There is _something_ about the text processing in cewe2pdf which means we do not get exactly the same output as the CEWE editor does, in particular our texts seem to be very very slightly wider (in some cases?). That means we can get an extra word wrap in a tightly fitting frame, which can introduce a new line and thereby increase the height.

**Comment by AnEnglishmanInNorway** [comment] 2020-12-18 09:35
@bash0 How about merging in pull request https://github.com/bash0/cewe2pdf/pull/57 and closing issues 56 and 58? I also wonder if it might be possible to open up for others to help with the administration if you're not particularly active? I'd like to be able to assign issues to myself, at least, so people know I've picked them up.

**Closed** 2020-12-18 09:43 UTC

**Comment by steff517** [comment] 2020-12-18 10:16
I con confirm that it works now! Thanks
