### ISSUE TITLE
cannot find cewe installation folder in cewe_folder.txt (Linux)

### ISSUE THREAD

**Issue by staaash** [bash0/cewe2pdf#22] opened 2020-04-07 11:57 UTC
Hi there. I tried three variations here, none worked (yet):

`/home/myusername/CEWE/My\ CEWE\ PHOTOBOOK/`

and

`"/home/myusername/CEWE/My CEWE PHOTOBOOK"`

and

`/home/myusername/CEWE/My CEWE PHOTOBOOK`

Any idea how to resolve?

**Comment by BarchSteel** [comment] 2020-04-26 12:29
It can't reproduce the problem.
I tested on Debian GNU/Linux 10 (buster)
I have installed CEWE FOTOWELT 07.00.02 into
/home/jotzie/CEWE/CEWE FOTOWELT/

You have to create the cewe_folder.txt either in the folder where cewe2pdf.py is, or where your .mcf file is.
The contents of my cewe_folder.txt is just one line with the plain path:
/home/USER/CEWE/CEWE FOTOWELT/

**Comment by AnEnglishmanInNorway** [comment] 2020-05-12 07:00
I think we should close this now. I haven't checked out the handling of cewe_folder.txt, but we are in any case moving towards the more flexible cewe2pdf.ini file, in which it is quite OK to use spaces in the folder names. Take a look at https://github.com/bash0/cewe2pdf/blob/master/cewe2pdf.ini, where you can see the (my) cewe_folder specified with spaces.

**Comment by AnEnglishmanInNorway** [comment] 2021-02-02 13:29
Closed as part of an administrative clean-up, a) because it is indicated as not having been reproduceable and b) because nobody complained when I suggested closing it about 9 months ago

**Closed by AnEnglishmanInNorway** 2021-02-02 13:29 UTC
