### ISSUE TITLE
Install requirements on Win10 (64bit)

### ISSUE THREAD

**Issue by bmffb** [bash0/cewe2pdf#64] opened 2021-01-15 11:51 UTC
I am trying to get your Python scrip running. I have Python 2.7 and pip installed.
With all required packages (lxml, reportlab ...) I am running into problems with missing other packages.
Is your script usable with a Python 2.7 setup?

**Comment by BarchSteel** [comment] 2021-02-02 14:33
To be honest, I don't know if it can run with Python 2.7. This version is quite old an deprecated, and I would not assume anybody has time to support it.
If you want to try Cewe2pdf under Windows 10, the easiest start is to use the Anaconda "Individual Edition" Python 3.8 distribution, and follow the instructions on the main page of this repository.

**Comment by AnEnglishmanInNorway** [comment] 2021-02-24 09:26
I finally got around to trying to freeze a version of the latest and greatest, but no luck for me either. 
- Windows 10 x64, latest update. 
- python -V in the anaconda window reports Python 3.7.6
I followed the pyinstaller instructions on https://github.com/bash0/cewe2pdf/blob/master/build_a_compiled_version.md to the letter, with no apparent oddities apart from one exception because cairo.dll was not in _C:\...\anaconda3\Library\bin_. I found it in _D:\Users\pete\Source\GitHub\vcpkg\installed\x64-windows\bin_, which probably reflects the fact that when I first joined this project some years back I couldn't get cairo installed without building it myself. Of course this might be the cause of my problem but the last line of the traceback implies that it might be something simpler:
```
(base) D:\Users\pete\Source\GitHub\cewe2pdf\dist\cewe2pdf>cewe2pdf.exe  d:\users\pete\Documents\Fotobooks\PhotoAlbum2020.mcf
Traceback (most recent call last):
  File "cewe2pdf.py", line 81, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "d:\Users\pete\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "clpFile.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "d:\Users\pete\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\cairosvg\__init__.py", line 38, in <module>
  File "pathlib.py", line 1216, in read_text
  File "pathlib.py", line 1203, in open
  File "pathlib.py", line 1058, in _opener
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Users\\pete\\Source\\GitHub\\cewe2pdf\\dist\\cewe2pdf\\VERSION'
[19464] Failed to execute script cewe2pdf
(base) D:\Users\pete\Source\GitHub\cewe2pdf\dist\cewe2pdf>
```
Here it claims that there is a VERSION file missing in the same directory as the generated exe, and that is certainly true. 
How would that file get there?

**Comment by AnEnglishmanInNorway** [comment] 2021-02-24 09:27
Sorry, sorry. Hit the close button. This is not closed at all, I just added more info.

**Comment by BarchSteel** [comment] 2021-02-28 15:43
I think you skipped step 3: Copy the VERSION file from anaconda3\Lib\site-packages\cairosvg to dist\cewe2pdf"
You can also just create a text file VERSION and put a version number in it, like 2.5.1

If not, you can patch the cairosvg package to ignore the file.

**Comment by AnEnglishmanInNorway** [comment] 2021-02-28 20:44
You are so right, how embarrassing. Thank you. 
I tested the "installation package" by copying our _unittest_fotobook.mcf_ with its associated data folder plus _cewepdf.ini_ and _additional_fonts.txt_ to a temp directory, and then executing _dist\cewe2pdf\cewe2pdf.exe_ from a standard windows cmd prompt in that temp directory (to be sure I had no "local directory" effects) and everything worked as expected. So a zip of dist\cewe2pdf\ could be copied to and executed on a similar machine to mine. 
I'm a bit inclined to agree with you about not supporting _cewe2pdf_ on Python 2.7, so I'd personally be happy to see this issue closed.

**Comment by AnEnglishmanInNorway** [comment] 2024-04-12 10:36
Tidying up, I'm prepared to close this now on the basis of it not being relevant any more
- Python 2.7 is really out of the question
- With upgraded versions of the packages we use pyinstaller will now make an exe which can be transported elsewhere and used with no other installation required.

**Closed by AnEnglishmanInNorway** 2024-04-12 10:36 UTC
